const unusedStyles = {
  backfaceVisibility: props => props.backfaceVisibility,
  boxDecorationBreak: props => props.boxDecorationBreak,
  breakAfter: props => props.breakAfter,
  breakBefore: props => props.breakBefore,
  breakInside: props => props.breakInside,
  '@charset': props => props.charset,
  content: props => props.content,
  counterIncrement: props => props.counterIncrement,
  counterReset: props => props.counterReset,
  filter: props => props.filter,
  '@font-face': props => props.fontFace,
  '@font-feature-values': props => props.fontFeatureValues,
  imageOrientation: props => props.imageOrientation,
  imageRendering: props => props.imageRendering,
  imageResolution: props => props.imageResolution,
  '@import': props => props.import,
  '@keyframes': props => props.keyframes,
  '@media': props => props.media,
  pageBreakAfter: props => props.pageBreakAfter,
  pageBreakBefore: props => props.pageBreakBefore,
  pageBreakInside: props => props.pageBreakInside,
  perspective: props => props.perspective,
  perspectiveOrigin: props => props.perspectiveOrigin,
  resize: props => props.resize,
}

export default unusedStyles
